# Common included file for all makefiles in the project

CC       	= gcc
CXX		= g++
CFLAGS   	= -g -Wall -Wno-unused-variable -DGCC 
CXXFLAGS   	= -g -Wall -Wno-unused-variable -DGCC -std=c++11
#CFLAGS   	= -O2 -Wall -Werror
#CXXFLAGS   	= -O2 -Wall -Werror
AR		    = ar
MAKE        = make
